### ISSUE TITLE
Sample missing files?

### ISSUE THREAD

**Issue by axilesoft** [Microsoft/groove-api-sdk-csharp#11]
Error		Task 'ValidateAppxManifestItems' failed. Could not find file 'S:\Windows-universal-samples-master\groove-api-sdk-csharp-master\samples\UniversalApplication\Package.appxmanifest'.	GrooveApiUniversalSamples

**Comment by bfreydier** [comment]
You first need to copy it from the /samples directory then associate your app to the store.
I just updated the [README file](https://github.com/Microsoft/groove-api-sdk-csharp/blob/master/README.md).

Thanks,
