### ISSUE TITLE
How to do a combined Artist / Track search?

### ISSUE THREAD

**Issue by MagnusJohansson** [Microsoft/groove-api-sdk-csharp#13]
I have been trying, without success to do a combined search for Artist and Track.
Let's say I want to find the Album on which a specific song appears, e.g. Artist "Michael Jackson", Track: "Human Nature".

Sure, one could do 2 requests, 1 for the artist and one for the tracks, but especially for the tracks one would need to do an "infinite" maxItems (since there could be potentially thousands of matching tracks) and then try to match the track to the artist.
Not very efficient.

How can I do a single Search request to find that?

The Amazon API is capable of this, by searching with the term "Michael Jackson - Human Nature".

Any ideas or suggestions?

**Comment by bfreydier** [comment]
Hello,

This feature is in our backlog, it should come soon.
In the meantime, the heuristic we'd recommend is to do a single track search on "[Artist Name] [Track Name]" (so in your example "Michael Jackson Human Nature")

Thanks

**Comment by MagnusJohansson** [comment]
Hi @bfreydier ,

thanks, seems to work ok.
