### ISSUE TITLE
Playlist fetched for any mood is the same.

### ISSUE THREAD

**Issue by dolbyarun** [Microsoft/groove-api-sdk-csharp#14]
Tested using the test method BrowsePlaylistsByMoodOrActivity.

For all mood type like "Happy", "Chill" etc, the returned playlists are same and the image url for all return 404.

**Comment by bfreydier** [comment]
Thanks for reporting this.

- For the same playlists returned: we fixed a bug on the client SDK (https://github.com/Microsoft/groove-api-sdk-csharp/pull/15)
- For the image urls returning 404s: we're working on a server side fix

**Comment by dolbyarun** [comment]
Tested and closing. (bow)
