### ISSUE TITLE
How tu use token

### ISSUE THREAD

**Issue by olivierHen** [Microsoft/groove-api-sdk-csharp#17]
Hi folks !

First of all, thank you very much ! I'm currently trying to use you lib for Asp.net core application and this works quite well, except the fact that I don't understand how to use the token authentication ... 

Can you help me please ?

Thank you,
Olivier

**Comment by olivierHen** [comment]
Actually, when I try to run the Test Project inside the sdk, I can't reach my playlists so I have 3 tests that fails... 

However, I have set the App.config file with my credentials and my Beaver token ...

**Comment by Seji64** [comment]
Hi, i actually trying the same as olivierHen and also stuck at using the token. It would be great if some can provide some tipps or example :-)

**Comment by olivierHen** [comment]
well ... I understand now why this thread is dead ... 

RIP Groove :'(
