### ISSUE TITLE
Artist Id appears incorrect when browsing collection

### ISSUE THREAD

**Issue by ThePyrobri** [Microsoft/groove-api-sdk-csharp#6]
Hi,
I am trying to write some code that matches new releases with artists in my current collection.
The code is working but there appears to be a mismatch in the Artist.Id from the browse ContenetResponse.
I took Bon Jovi as an example.
When an album appeared in the New Releases endpoint I got the following id:
music.790F0000-0200-11DB-89CA-0019B92A3933
This appears correct and is the same Id shown in the address bar when browsing this artist on the Groove Web Player.
However when I get the content response it shows the following Id:
music.AQILAAAPeQACYm9-5tsBoRw
This is a very different looking Id to any others I have encountered and obviously does not match the one above.
To further add to this the Artist that is downloaded does appear to have the correct Id in its ImageUrl and its Deep Link.
I have added a screen shot showing this. Now I can code around this by getting the Id from the ImageUrl instead but what is the reason for the short Id here and is it a bug?
I have checked multiple artists and they are all showing the wrong (or at least unexpected) Id when using browse.
Cheers
![2017-01-25_li](https://cloud.githubusercontent.com/assets/24525162/22286696/f080be72-e2e7-11e6-8f92-d05f62a36d4c.jpg)

**Comment by bastte** [comment]
Hi ThePyrobri,

This is expected. The "complex" id you're getting when browsing (music.AQILAAAPeQACYm9-5tsBoRw) internally points to the same content than music.790F0000-0200-11DB-89CA-0019B92A3933, but it has more data encoded in it. This allows us to handle scenarios that mix catalog / collection content. This is indicated by the "Source" property in the response : in the browse call you get the result from your collection, whereas in the new releases call you get the result from our catalog.

I'm thinking of a few ways to make your scenario work. The most stable would be to use the collection id (music.AQILAAAPeQACYm9-5tsBoRw) and make a lookup call specifying that you want the "catalog" source and the response will contain the guid id you expect. But this means making more calls (even though you can batch them). Another solution which doesn't involve making more calls is to either match on Artist Name + Album Name (which is most likely unique) or extract the guid id from the ImageUrl or Link as you suggested.

Cheers,

**Comment by ThePyrobri** [comment]
OK that makes sense. I was thinking that there maybe was some sort of difference between catalog and collection ids but we cant tell from this side of the fence :)
Yes to avoid more calls (I want to process every artist in the collection every time I run a compare) I will just grab the id from the deep Link instead.
Maybe this would be the ideal place to make use the OtherIds property on the main Content object?
I have only ever seen this null so not currently sure if it is in use?

**Comment by bfreydier** [comment]
Hi,

We recently added an entry in the "OtherIds" array which contains the "simple" id for each item, just grab it from the "music.catalog" entry:

`"OtherIds"  : { "music.catalog" : "music.c61c0000-0200-11db-89ca-0019b92a3933"}`

Cheers
